- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: ansible-azurevm
      location: eastus
      tags:
          testing: testing
          delete: never

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ansible-azurevm
      name: testvn001
      address_prefixes: "10.10.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: ansible-azurevm
      name: subnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: testvn001

  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: ansible-azurevm
      allocation_method: Static
      name: publicip001

  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: ansible-azurevm
      name: secgroup001
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: ansible-azurevm
      name: testnic001
      virtual_network: testvn001
      subnet: subnet001
      public_ip_name: publicip001
      security_group: secgroup001

  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: ansible-azurevm
      name: testvm001
      vm_size: Standard_DS1_v2
      admin_username: azureadmin
      admin_password: "{{ 999999 | random | to_uuid }}"
      network_interfaces: testnic001
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04.0-LTS'
        version: latest