jobs:
- job: linux
  displayName: Run on Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    GOPATH: '$(system.defaultWorkingDirectory)/gopath'
    modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'
  steps:
  - script: |
      apt update && apt install -yq git make
      curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.sh | bash
      gofish init
      gofish install dep
      gofish install go
    displayName: 'install dependencies'
  - script: |
      mkdir -p '$(modulePath)'
      mv '$(system.defaultWorkingDirectory)/*' '$(modulePath)'
    displayName: 'setup workspace'
  - script: make build
    workingDirectory: '$(modulePath)'
    displayName: 'build'
  - script: make test
    workingDirectory: '$(modulePath)'
    displayName: 'run unit tests'
- job: windows
  displayName: Run on Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    PATH: 'C:\ProgramData\bin;C:\ProgramData\Chocolatey\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\'
    GOPATH: '$(system.defaultWorkingDirectory)\gopath'
    modulePath: '$(GOPATH)\src\github.com\$(build.repository.name)'
  steps:
  - powershell: |
      Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      choco install git make
      iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.ps1'))
      gofish init
      gofish install dep
      gofish install go
    displayName: 'install dependencies'
  - script: |
      shopt -s extglob
      mkdir -p '$(modulePath)'
      mv !(gopath) '$(modulePath)'
    displayName: 'setup workspace'
  - script: make build
    workingDirectory: '$(modulePath)'
    displayName: 'build'
  - script: make test
    workingDirectory: '$(modulePath)'
    displayName: 'run unit tests'
