#!/bin/sh

#set -eo pipefail

inputs="$(jq -r . < /dev/stdin)"

echo "inputs: $inputs"

action="$(echo "$inputs" | jq -r .installation.action)"
name="$(echo "$inputs" | jq -r .installation.name)"
greeting="$(echo "$inputs" | jq -r .parameters.greeting)"
names="$(echo "$inputs" | jq -r .parameters.names[])"

for name in $names; do
  echo "$greeting $name"
done

case $action in
    install)
    echo "Install action"
    ;;
    uninstall)
    echo "uninstall action"
    ;;
    upgrade)
    echo "Upgrade action"
    ;;
    downgrade)
    echo "Downgrade action"
    ;;
    status)
    echo "Status action"
    ;;
    *)
    echo "No action for $action"
    ;;
esac
echo "Action $action complete for $name"
